FROM python

WORKDIR /usr/src/repos/Coffee_project/TelegramBot/code/Telegrasm

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./Telegrasm.py" ]